### ISSUE TITLE
Query a user's balance

### ISSUE THREAD

**Issue by onumengine** [WakalaDAO/wakala-smart-contracts#2]
Define an external method that when called from a node, will return the user's balance as JSON

**Comment by steffenkrogmann** [comment]
hey @onumengine 
these open issues in the smart contract repo, can they be closed?
if yes, please close those assigned to you

**Comment by steffenkrogmann** [comment]
closing this @onumengine @Muhani99 
i thinks this is done, otherwise reopen.
