### ISSUE TITLE
Define a method for sending M-PESA

### ISSUE THREAD

**Issue by onumengine** [WakalaDAO/wakala-smart-contracts#6]
The method should be external, its parameter should be the amount of M-PESA the user wants to send and it should return a boolean representing the transaction's status - successful or failed

**Comment by GrandLegend** [comment]
Done.

**Comment by steffenkrogmann** [comment]
closing this @onumengine @Muhani99 
i thinks this is done, otherwise reopen.

@onumengine when someone reassigns an issue to you and you think it is done (you have what you need) please close that issue. Dont let them sit here.
